{
 "title": "Grott Growatt Monitor",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Growatt Actual ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "power ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "QMB2823261",
     "select": [
      [
       { "params": [ "pvgridpower" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power Actual",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "QMB2823261",
     "query": "SELECT \"power_used\"   AS \"dag\" FROM \"electricity\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "pvgridpower" ], "type": "field" },
       { "params": [ " / 10" ], "type": "math" },
       { "params": [ "dag" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "PV Voltage",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "QMB2823261",
     "select": [
      [
       { "params": [ "pv1voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "PV Temp",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "QMB2823261",
     "select": [
      [
       { "params": [ "pvtemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Grid Voltage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "QMB2823261",
     "select": [
      [
       { "params": [ "pvgridvoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Grid Frequency",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "QMB2823261",
     "select": [
      [
       { "params": [ "pvfrequentie" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Growatt Day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "alias": "power ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "QMB2823261",
     "select": [
      [
       { "params": [ "pvenergytoday" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Growatt Day",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "QMB2823261",
     "query": "SELECT \"power_used\"   AS \"dag\" FROM \"electricity\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "pvenergytoday" ], "type": "field" },
       { "params": [ " / 10" ], "type": "math" },
       { "params": [ "dag" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Growatt Total",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "QMB2823261",
     "query": "SELECT \"pvenergytotal\" / 10 FROM \"QMB2823261\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "pvenergytotal" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}