name: "Build docker images"

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    name: "Build images"
    runs-on: "ubuntu-latest"
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3.5.2
      -
        name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.5.0
      -
        name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Parse repository owner to lowercase
        env:
          OWNER: '${{ github.repository_owner }}'
        run: |
          echo "OWNER_LC=$(echo $OWNER | tr '[:upper:]' '[:lower:]')" >>${GITHUB_ENV}
      -
        name: Building the image CLI
        run: |
          docker buildx build --push \
          --tag ghcr.io/${OWNER_LC}/grott:debian \
          --tag ghcr.io/${OWNER_LC}/grott:latest \
          --platform linux/amd64,linux/arm64 .
          docker buildx build --push \
          --tag ghcr.io/${OWNER_LC}/grott:alpine \
          --platform linux/amd64,linux/arm64 --file Dockerfile-alpine .
